site_name: Hammer Game Documentation
repo_url: https://github.com/mammoth-games/hammer
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  favicon: img/site/hammer_small_red.png
  logo: img/site/hammer_small.png
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: red
      accent: pink
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: red
      accent: pink
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
    - pymdownx.highlight:
        linenums_style: pymdownx.inline
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys
    - admonition

nav:
  - client:
    - controllers:
      - character:
        - RagdollController: client/controllers/character/RagdollController.md
        - CharacterController: client/controllers/character/CharacterController.md
      - OnRuntimeController: client/controllers/OnRuntimeController.md
      - InputService: client/controllers/InputService.md
      - GameLoopController: client/controllers/GameLoopController.md
      - CameraController: client/controllers/CameraController.md
      - CrownController: client/controllers/CrownController.md
      - AudioController: client/controllers/AudioController.md
      - hammer:
        - HammerController: client/controllers/hammer/HammerController.md
        - HitController: client/controllers/hammer/HitController.md
      - TimerWallController: client/controllers/TimerWallController.md
      - UI:
        - ProgressBarController: client/controllers/UI/ProgressBarController.md
        - UserInterfaceController: client/controllers/UI/UserInterfaceController.md
        - KingIndicatorController: client/controllers/UI/KingIndicatorController.md
        - BamMeterController: client/controllers/UI/BamMeterController.md
    - modules:
      - Spring: client/modules/Spring.md
      - AbelianTable: client/modules/AbelianTable.md
      - GuiLib: client/modules/GuiLib.md
      - t: client/modules/t.md
      - Enumerator: client/modules/Enumerator.md
      - RaycastHitbox: client/modules/RaycastHitbox.md
      - NumberSpinner: client/modules/NumberSpinner.md
      - gizmo: client/modules/gizmo.md
    - Constants: client/Constants.md
  - misc:
    - art: misc/art.md
    - costumes: misc/costumes.md
  - index: index.md
  - server:
    - modules: server/modules.md
    - gamemodes: server/gamemodes.md
    - services:
      - hammers:
        - HitService: server/services/hammers/HitService.md
        - HammerService: server/services/hammers/HammerService.md
      - data:
        - ProfileService: server/services/data/ProfileService.md
        - PlayerCharacterService: server/services/data/PlayerCharacterService.md
      - gameplay:
        - MapService: server/services/gameplay/MapService.md
        - LobbyService: server/services/gameplay/LobbyService.md
        - GameLoopService: server/services/gameplay/GameLoopService.md
      - characters:
        - DeathService: server/services/characters/DeathService.md
        - RagdollService: server/services/characters/RagdollService.md
        - AvatarService: server/services/characters/AvatarService.md
      - general:
        - ClockService: server/services/general/ClockService.md
        - LightingService: server/services/general/LightingService.md
    - components:
      - HillComponent: server/components/HillComponent.md
      - KillBrickComponent: server/components/KillBrickComponent.md
      - RagdollBrickComponent: server/components/RagdollBrickComponent.md
      - RagdollComponent: server/components/RagdollComponent.md
      - LeaderboardComponent: server/components/LeaderboardComponent.md
      - BubbleComponent: server/components/BubbleComponent.md
      - UnragdollBrickComponent: server/components/UnragdollBrickComponent.md
  - utils: utils.md
