site_name: Hammer Game
nav:
    - Home: index.md
    - 'ServerStorage':
        - 'Services':
            - 'ServicesExample': 'services.md'
        - 'Modules':
            - 'ClientCast': 'ClientCast.md'
            - 'DataStore2': 'DataStore2.md'
            - 'ProfileService': 'ProfileService.md'
            - 'TimeUtils': 'TimeUtils.md'
        - 'Components':
            - 'BubbleComponent': 'BubbleComponent.md'
            - 'HillComponent': 'HillComponent.md'
            - 'KillBrickComponent': 'KillBrickComponent.md'
            - 'LeaderboardComponent': 'LeaderboardComponent.md'
            - 'RagdollBrickComponent': 'RagdollBrickComponent.md'
            - 'RagdollComponent':
              - 'RagdollComponent': 'RagdollComponent.md'
              - 'BuildConstraintsRig': 'BuildConstraintsRig.md'
              - 'RagdollConstants': 'RagdollConstants.md'
            - 'UnragdollBrickComponent': 'UnragdollBrickComponent.md'
    - 'ReplicatedStorage':
        - 'Knit':
            - 'Components':
                - 'LobbyCountdown': 'LobbyCountdown.md'
            - 'Controllers':
                - 'ControllerExample': 'blank.md'
            - 'Modules':
                - 'ModulesExample': 'blank.md'
            - 'Util':
                - 'UtilExample': 'blank.md'

repo_url: https://github.com/mammoth-games/hammer
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  favicon: img/hammer_small.png
  logo: img/hammer_small.png
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: red
      accent: pink
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: red
      accent: pink
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode