site_name: Hammer Game Documentation
repo_url: https://github.com/mammoth-games/hammer
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  favicon: img/site/hammer_small_red.png
  logo: img/site/hammer_small.png
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: red
      accent: pink
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: red
      accent: pink
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
    - pymdownx.highlight:
        linenums_style: pymdownx.inline
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys
    - admonition