site_name: Hammer Game
nav:
    - Home: index.md
    - Server:
        - Services:
            - Characters: 
                - DeathService: server/services/characters/DeathService.md
                - RagdollService: server/services/characters/RagdollService.md
            - Data:
                - PlayerCharacterService: server/services/data/PlayerCharacterService.md
                - ProfileService: server/services/data/ProfileService.md
            - Gameplay:
                - GameLoopService: server/services/gameplay/GameLoopService.md
                - LobbyService: server/services/gameplay/LobbyService.md
                - MapService: server/services/gameplay/MapService.md
            - General:
                - ClockService: server/services/general/ClockService.md
            - Hammers:
                - HammerService: server/services/hammers/HammerService.md
                - HitService: server/services/hammers/HitService.md
        - Modules: server/modules.md
        - Components:
            - BubbleComponent: server/components/BubbleComponent.md
            - HillComponent: server/components/HillComponent.md
            - KillBrickComponent: server/components/KillBrickComponent.md
            - LeaderboardComponent: server/components/LeaderboardComponent.md
            - RagdollBrickComponent: server/components/RagdollBrickComponent.md
            - RagdollComponent: server/components/RagdollComponent.md
            - UnragdollBrickComponent: server/components/UnragdollBrickComponent.md
        - Game Modes: server/gamemodes.md
#        - ServerRuntime: server/services/example.md
    - Client:
        - Controllers:
            - Example: client/controllers/example.md
        - Modules:
            - RaycastHitbox: client/modules/RaycastHitbox.md
        - Components:
            - LobbyCountdownComponent: client/components/LobbyCountdownComponent.md
    - Knit:
        - Components:
            - LobbyCountdown: knit/components/LobbyCountdown.md
        - Controllers:
            - Characters:
                - CharacterController: knit/controllers/character/CharacterController.md
                - RagdollController: knit/controllers/character/RagdollController.md
            - Hammer:
                - HammerController: knit/controllers/hammer/HammerController.md
                - HitController: knit/controllers/hammer/HitController.md
            - UI:
                - KingIndicatorController: knit/controllers/ui/KingIndicatorController.md
                - ProgressBarController: knit/controllers/ui/ProgressBarController.md
                - UserInterfaceController: knit/controllers/ui/UserInterfaceController.md
            - AudioController: knit/controllers/AudioController.md
            - CameraController: knit/controllers/CameraController.md
            - CrownController: knit/controllers/CrownController.md
            - GameLoopController: knit/controllers/GameLoopController.md
            - InputService: knit/controllers/InputService.md
            - OnRuntimeController: knit/controllers/OnRuntimeController.md
            - TimerWallController: knit/controllers/TimerWallController.md
        - Modules:
            - GuiLib: knit/modules/GuiLib.md
            - Enumerator: knit/modules/Enumerator.md
            - NumberSpinner: knit/modules/NumberSpinner.md
            - RaycastHitbox: knit/modules/RaycastHitbox.md
            - AbelianTable: knit/modules/AbelianTable.md
            - Spring: knit/modules/Spring.md
            - gizmo: knit/modules/gizmo.md
            - t: knit/modules/t.md
        - Version: knit/Version.md
        - Constants: knit/Constants.md
        - KnitClient: knit/KnitClient.md
        - KnitServer: knit/KnitServer.md
    - Utils: utils.md

repo_url: https://github.com/mammoth-games/hammer
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  favicon: img/hammer_small.png
  logo: img/hammer_small.png
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: red
      accent: pink
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: red
      accent: pink
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
    - pymdownx.highlight:
        linenums_style: pymdownx.inline
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys