site_name: Hammer Game
nav:
    - Home: index.md
    - 'Services':
        - 'ServicesExample': 'services.md'
    - 'Controllers':
        - 'ControllerExample': 'controllers.md'
    - 'Modules':
        - 'ModulesExample': 'modules.md'
    - 'Components':
        - 'BubbleComponent': 'BubbleComponent.md'
        - 'HillComponent': 'HillComponent.md'
        - 'KillBrickComponent': 'KillBrickComponent.md'
        - 'LeaderboardComponent': 'LeaderboardComponent.md'
        - 'RagdollBrickComponent': 'RagdollBrickComponent.md'
        - 'RagdollComponent': 'RagdollComponent.md'
        - 'UnragdollBrickComponent': 'UnragdollBrickComponent.md'
    - 'GameModes':
        - 'GameModesExample': 'gamemodes.md'
repo_url: https://github.com/mammoth-games/hammer
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  favicon: img/hammer_small.png
  logo: img/hammer_small.png
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: red
      accent: pink
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: red
      accent: pink
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode