name: Build nav and gh-deploy
on:
  push:
    branches:
      - merge
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          python build_nav.py
          pip install mkdocs-material
          mkdocs gh-deploy --force